feat: Add Arseeding support
labscommunity/protocol-land-sync pull request #22
Opened 2024-01-31 06:54 UTC by pawanpaudel93

## Summary

This PR adds ArSeeding support to sync repositories to Protocol Land.

## How to test
1) Deposit some amount of supported Arweave tokens to [EverPay](https://everpay.io/). Supported tokens are: `['XYZ', 'ARDRIVE', 'PIA', 'VRT', 'U', 'STAMP', 'AR']`
2) Add the following environment variables to GH action or .env:

```dosini
WALLET=''
REPO_TITLE=''
REPO_DESCRIPTION=''
STRATEGY='ARSEEDING'
ARSEEDING_TOKEN_SYMBOL='AR'
```
3) Follow the steps in README.md

2024-01-31 21:04 UTC, 7i7o requested changes
tACK
It works. Arseeding is a little slower than turbo or irys, so the repo can take a minute or two to show correctly in PL.
Left a comment on the `arseeding.ts` file for important changes

2024-01-31 21:04 UTC, 7i7o commented on src/lib/arseeding.ts
Is there an option for arseeding-js to omit logging the key to console? That will be saved in the gh action logs, exposing it for anyone with access to it

2024-02-01 05:05 UTC, pawanpaudel93 commented on src/lib/arseeding.ts
So i figured out where the logging is occuring. It's occuring in `everpay-js` sdk. I have now silenced the logging from `arseeding.ts`.

2024-02-01 11:19 UTC, kranthicodes submitted a review, later dismissed
tACK

2024-02-01 11:52 UTC, 7i7o submitted a review, later dismissed
tACK
LGTM! 🚀

2024-02-01 12:08 UTC, 7i7o approved these changes
LGTM! 🚀

2024-02-01 12:21 UTC, merged